### ISSUE TITLE
APK availability

### ISSUE THREAD

**Issue by IzzySoft** [watea/RadioUpnp#1]
First thanks for making such a great app available open-source! Would you also consider making it available to those Android users without access to Google Play – e.g. by attaching the APK to its corresponding [release](https://github.com/watea/RadioUpnp/releases) (as that's where we usually look first)? :pray:

**Comment by watea** [comment]
Hi, thanks for return. Good idea, I will add this for the next release.

**Comment by IzzySoft** [comment]
Great, thanks! Please send me a ping here again once it's available. I'll then "spread the word further" :smiley:

**Comment by watea** [comment]
Hi, as no work is currently scheduled in the next week, I have simply generated a signed .apk and commit it. Regards

**Comment by watea** [comment]
Hi , as I don't schedule any further work in the next weeks, I simply add a
signed .APK to GitHub. Regards

**Comment by IzzySoft** [comment]
Thanks a lot @watea – adding it to [my repo](https://apt.izzysoft.de/fdroid) then.

Just a suggestion: you can [add release notes to your tags in Github](https://github.com/watea/RadioUpnp/releases) (same for Gitea, GitLab etc) and attach the APK there. Advantages: 1) that's where users look first and 2) it doesn't "bloat" the repo itself (when cloning, the APKs and their history would not be copied along).

RadioUpnp will [show up here](https://apt.izzysoft.de/fdroid/index/apk/com.watea.radio_upnp) with the next sync around 6 pm UTC today. If you wish, I can send you the metadata I've set up (based on your app's Playstore presence: description, screenshots etc) in [fastlane format](https://gitlab.com/-/snippets/1895688) as PR, so you're in full control of how your app will be presented (changes would be picked up with each new APK release you make available), just let me know.

As the APK is available now, this issue is basically solved – so feel free to close, or to keep it open to address my suggestions if you wish :wink: Thanks again!

PS: If you like the new presence for your app (where users with no Playstore access can install your app from and keep it updated, as they will receive update notifications using any [F-Droid client](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181)), be welcome to link there from your Readme. There're even [badges available](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for this purpose :smiley:

**Comment by watea** [comment]
Ok thanks, very interesting. I will look at that next time I spend some
time on the app.

Regards

**Comment by watea** [comment]
Ok thanks, very interesting. I will look at that next time I spend some
time on the app.

Regards

**Comment by IzzySoft** [comment]
Whenever it fits in, sure. Let me know if/when you want the fastlane structures, my offer stands.

**Comment by IzzySoft** [comment]
Besser spät als nie 🤣 [Hier ist der PR](https://github.com/watea/RadioUpnp/pull/34) 🤗
