### ISSUE TITLE
Please remove bad components

### ISSUE THREAD

**Issue by Wjxfi** [watea/RadioUpnp#11]
![c87fc58d-e248-40d9-bce0-f44150bbe144.jpg](https://github.com/watea/RadioUpnp/assets/113500363/21a90aa2-c060-4ba0-9b31-181cf0a8bcb4)

**Comment by watea** [comment]
Thanks for feedback.
Actually I don't really understand.
Could you be more explicit on the non-free dependencies? All libraries used are open source.

**Comment by watea** [comment]
More donation links added: liberapay & paypal.
