### ISSUE TITLE
Lock screen has no pause button

### ISSUE THREAD

**Issue by ovizii** [watea/RadioUpnp#14]
Not sure if this is related to this app but when I use other music players, on my lock screen I see info about what is playing and can also pause music. 

With this app, I see what is playing, but there's no pause or stop button.

Is there anything you can do about it or am I doing something wrong?

**Comment by watea** [comment]
Thanks for feedback.
I'm afraid I can't do a lot...
As experienced on several devices, it seems to be an Android and/or brand custom layer trouble. Lock screen or up screen trailer notification layout is not handled by app; on some Android version/devices it seems not to work as specified, and making device specific bug workaround is out of scope of this app.
Could you either give Android version and device brand?
Thanks

**Comment by ovizii** [comment]
I udnerstand, thanks for taking the time to explain. 

I am using this ROM: https://evolution-x.org/ Android 13 with the security update of 05 May 2023
