### ISSUE TITLE
Connection error swedish stations "Sveriger Radio P1, P2, P3 etc

### ISSUE THREAD

**Issue by rimbo8123** [watea/RadioUpnp#15]
The last release in mid september causes a connection error with swedish stations "Sveriges Radio  - P1, P2, P3...". What can be wrong?

**Comment by watea** [comment]
Hi,


Thanks for feedback.
My own test with release 2.63.22 shows no trouble:

Sveriges Radio - P1
URL: http://stream.dar.fm/5005

You may test if you use the right URL.

Remember you can also send me a report:
Try again and then 
Menu > Report

Regards

**Comment by watea** [comment]
Hi,

Ok perhaps some data corruption occurred (should not happen), or the actual URL changed... 

You're welcome!



Regards
