### ISSUE TITLE
[IDEA] Import from CSV

### ISSUE THREAD

**Issue by hicks86** [watea/RadioUpnp#17]
Hello,

Recently discovered your app on the weekend and it's perfect for my use case. I have a couple of old WiFi speakers where the company app has become no longer maintained. Anyways I want an app that can easily push music streams to them and hey your app does that.

I just wondered as you have an export feature that you'd consider adding an Import from CSV feature. This would help a lot with manually inputting steams especially if you have a lot to add (I use DI.FM and they have their own streams URL for each of the channels to use with 3rd party apps etc). 

Just a thought, happy to discuss.

**Comment by watea** [comment]
Hi,

Thanks for this feedback.
Glad to hear this app is useful.

As you can see there's some other improvement requests, it is a matter of priority.

Import from CSV is not a big deal. Yet for now the few hours I spend on that are dedicated to the most important #13 which is a threat of app deprecation.

If you have some skills in developing, the all app data is stored in a simple JSON file you may access with development tool, and add all the radio item you want.

Regards,
Stephane

**Comment by watea** [comment]
Hi,

Release [https://github.com/watea/RadioUpnp/tree/V2.71.00](url) implements .json import / export.

Regards

**Comment by watea** [comment]
Added in [V2.71.18](https://github.com/watea/RadioUpnp/releases/tag/V2.71.18)
