### ISSUE TITLE
question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [watea/RadioUpnp#18]
The scanner at IzzyOnDroid reported:

```
! repo/com.watea.radio_upnp_27100.apk declares sensitive permission(s):
  android.permission.READ_EXTERNAL_STORAGE
! repo/com.watea.radio_upnp_27100.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Coud you please clarify what the storage permissions (READ+WRITE) are needed for? The app description gives no clue, and streaming should not need full storage access.

As for the `DEPENDENCY_INFO_BLOCK`, that can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by watea** [comment]
Hi IzzySoft,



Thanks for feedback.

/ Storage:
Needed for radio database .json and .csv export on local file, that has been asked by some users.
Please don't hesitate to show a better way to do this, I didn't spend much time on this by-side feature.

/ DEPENDENCY_INFO_BLOCK:
OK will be added in next release.


Regards,
Stephane

**Comment by IzzySoft** [comment]
> Needed for radio database .json and .csv export on local file, that has been asked by some users.
> Please don't hesitate to show a better way to do this, I didn't spend much time on this by-side feature.

That sounds like a single location should suffice, and you won't need access to all the storage? Then maybe SAF (Storage Access Framework) could easily deal with it. On first access, invoke the file picker to choose a location, then use that; would give the app access to the selected directory and everything inside (including sub-directories).

So shall we leave this open until you had a look? Let me just know then if it's viable for you. If so, you take that approach – if for some reason that's no option, we'd put the storage permission to the app's "green list" here with a proper explanation.

> DEPENDENCY_INFO_BLOCK

Thanks!

**Comment by watea** [comment]
> That sounds like a single location should suffice, and you won't need access to all the storage? Then maybe SAF (Storage Access Framework) could easily deal with it. On first access, invoke the file picker to choose a location, then use that; would give the app access to the selected directory and everything inside (including sub-directories).

You're right; actually already used for read access - frankly speaking without knowing using SAF (like Monsieur Jourdain, if it is not to shame Molière ;)), I have to do the same for write.
As soon as I find time.

Thanks!

**Comment by IzzySoft** [comment]
Fingers crossed then, thanks! For the meantime, I've added both permissions to your app's green list with the explanation they are *used* (not required) for that. Once you've removed them in favor of SAF, my scanner should report that to me and I can remove them from the green list again as well.

Thanks! I'm leaving this issue open for the SAF task – feel free to close if you prefer that.

**Comment by watea** [comment]
Fixed in [https://github.com/watea/RadioUpnp/releases/tag/V2.71.04](url)
