### ISSUE TITLE
wrong APK at latest tag?

### ISSUE THREAD

**Issue by IzzySoft** [watea/RadioUpnp#2]
Looks like the APK at v2.61.17 is the same one as that on v2.61.14 (identifies with the same `versionCode` and is even binary identical). Could it be you accidentally attached the wrong file? Could you please replace it with the correct one? Thanks in advance!

**Comment by IzzySoft** [comment]
@watea any chance? Or shall I rather disable update-checks for your app in my repo to avoid the error being reported over and again? :wink:

**Comment by watea** [comment]
@IzzySoft Sorry for late answer, was not so available those last days. Fixed; should be fine now.

**Comment by IzzySoft** [comment]
Confirmed – thanks!
