### ISSUE TITLE
Radio garden integration broken

### ISSUE THREAD

**Issue by mgitp** [watea/RadioUpnp#20]
Share from radio garden to radioupnp ends with error message "internal error: radio modification failed"
Radio garden api might have changed.
Related log entries:
***
12-05 12:13:51.403 29920 29920 D RadioGardenController: Radio Garden intent received
12-05 12:13:51.405 29920 29920 D RadioGardenController: ClipData: ClipData.Item { T:Listen to KAKU-LP 88.5 FM from Kahului HI live on Radio Garden: https://radio.garden/listen/kaku-lp-88-5-fm/N4bb4RrU }
....
12-05 12:13:51.569 29920 30818 D RadioGardenController: handle asynchronous exception
12-05 12:13:51.569 29920 30818 D RadioGardenController: org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at org.json.JSON.typeMismatch(JSON.java:112)
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at org.json.JSONObject.<init>(JSONObject.java:168)
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at org.json.JSONObject.<init>(JSONObject.java:181)
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at com.watea.radio_upnp.activity.RadioGardenController.getJson(RadioGardenController.java:118)
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at com.watea.radio_upnp.activity.RadioGardenController.handle(RadioGardenController.java:189)
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at com.watea.radio_upnp.activity.RadioGardenController.lambda$onNewIntent$3$com-watea-radio_upnp-activity-RadioGardenController(RadioGardenController.java:138)
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at com.watea.radio_upnp.activity.RadioGardenController$$ExternalSyntheticLambda4.run(D8$$SyntheticClass:0)
12-05 12:13:51.569 29920 30818 D RadioGardenController: 	at java.lang.Thread.run(Thread.java:919)
***

**Comment by watea** [comment]
Well done, Radio Garden URL has actually changed to https scheme.
Fixed in this [commit](https://github.com/watea/RadioUpnp/commit/d68eed4e9356ef70448049f0753884f2aadbc288).

Will be added in next release.

Thanks!
