### ISSUE TITLE
Don't see title and author of the song

### ISSUE THREAD

**Issue by trev0r-STA** [watea/RadioUpnp#4]
Hello
Nice application.
A little problem with it: I can't get the title and the author of the song showing. Am I missing something ? Or is it a feature ?
Thanks
![_20230202_140121](https://user-images.githubusercontent.com/17881601/216332250-feb1b3f1-4a32-451c-8f94-eeb0d4dfd08f.png)

**Comment by watea** [comment]
Hi,


Title and singer only appears when the radio server support ICY standard.

For FIP it seems not to be the case.


Regards.
