### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by xmha97** [watea/RadioUpnp#6]
Please add the light theme to the app.
Thanks 🙏

**Comment by watea** [comment]
Yes I know it should be done, thanks for recalling that!
If I ever find time ;)

**Comment by ovizii** [comment]
Yes please. The current theme has a very low contract unfortunately, I can barely read the dark grey on black text. This is what it looks like when I add a station.

![Screenshot_20230707-102028_RadioUpnp](https://github.com/watea/RadioUpnp/assets/837902/3e36d61a-724e-426b-8b60-e9f67162e8be)

**Comment by watea** [comment]
Thanks for feedback.
Not done yet because the current layout is mostly based on default colours, which was the easiest way.
Tailoring that requires to adjust quiet a lot of features, and it was not the priority till now.

**Comment by watea** [comment]
Hi,

Layout improvement and theme selection is added in [https://github.com/watea/RadioUpnp/tree/V2.71.00](url).

Regards.
