### ISSUE TITLE
Why would this station not work

### ISSUE THREAD

**Issue by dln949** [watea/RadioUpnp#8]
This station gives a connection error:  

[https://hls-01-radiorecord.hostingradio.ru/record-hbass/96/playlist.m3u8](url)

**Comment by watea** [comment]
Thanks for feedback.

This is a m3u URL, its a format for playlist.
This URL gives:


#EXTM3U
#EXT-X-VERSION:6
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:2915857
#EXTINF:4.92263,
https://hls-08-storage.hostingradio.ru/record-hbass/96/out2915857.ts
#EXTINF:4.92263,
https://hls-08-storage.hostingradio.ru/record-hbass/96/out2915858.ts
#EXTINF:4.92263,
https://hls-08-storage.hostingradio.ru/record-hbass/96/out2915859.ts
#EXTINF:4.92263,
https://hls-08-storage.hostingradio.ru/record-hbass/96/out2915860.ts
#EXTINF:4.92263,
https://hls-08-storage.hostingradio.ru/record-hbass/96/out2915861.ts
#EXTINF:4.92263,
https://hls-08-storage.hostingradio.ru/record-hbass/96/out2915862.ts


Where the .ts file are the actual audio files.
Unfortunately, what RadioUpnp expects is a single streaming URL, not several ones. As far as I understand this cannot work, even if I change the way I decode m3u file (at this time only .m3u format is recognized, not .m3u8).

Where did you get this URL?

**Comment by watea** [comment]
HLS format is not supported by current architecture.
Should be reworked.

**Comment by watea** [comment]
Some attempt with ExoPlayer are not successful; changing MediaItem options depending on HTTP header (mime type).
Solution should be more complex...

**Comment by watea** [comment]
Added in release #V2.63.30
